# Module 6 Challenge

## ``Housing Rental Analysis for San Francisco``

In [1]:
# Required imports

import pandas as pd
import geoviews
from pathlib import Path
import hvplot.pandas

c:\Users\prath\anaconda3\envs\dev\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


### Importing the data 

In [2]:
# Reading sfo_neighborhoods_census_data.csv file

sfo_path = Path(r"C:\Users\prath\UofT\UTOR-VIRT-FIN-PT-08-2023-U-LOLC\06-PyViz\Unit 6 Homework\Instructions\Starter_Code\Resources\sfo_neighborhoods_census_data.csv")

sfo_data_df = pd.read_csv(sfo_path)

# Reviewing the first and last five rows of the DataFrame

display(sfo_data_df.head())

display(sfo_data_df.tail())


year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

year            neighborhood  sale_price_sqr_foot  housing_units  \
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

---

### Calulating and Plotting the Housing Units per Year

Step 1: Using `groupby` function to group the data by year. Aggregating the results by the `mean` of the groups.

In [3]:
# Creating a numerical aggregation that groups the data by the year and then averages the results.

housing_units_by_year = sfo_data_df.drop(columns=["sale_price_sqr_foot", "gross_rent"]).groupby("year").mean()

# Reviewing the DataFrame

housing_units_by_year


C:\Users\prath\AppData\Local\Temp\ipykernel_25004\2899990041.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  housing_units_by_year = sfo_data_df.drop(columns=["sale_price_sqr_foot", "gross_rent"]).groupby("year").mean()


housing_units
year               
2010       372560.0
2011       374507.0
2012       376454.0
2013       378401.0
2014       380348.0
2015       382295.0
2016       384242.0

Step 2: Using the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. The x-axis represents the `year` and the y-axis represents the `housing_units`.

Step 3: Styling and formatting the line plot to ensure a professionally styled visualization.

In [4]:
# Creating a visual aggregation to explore the housing units by year

display(housing_units_by_year.hvplot.bar(
    x="year",
    y="housing_units",
    xlabel="Year",
    ylabel="Housing Units",
    rot=0,
    color = "Blue",
    yformatter = "%.0f",
    height = 450,
    width = 750,
    fontscale = 1.3,
    ylim = (364800, 385900),
    hover_color = "Grey",
    title="Housing Units in San Francisco from 2010 to 2016"
))


:Bars   [year]   (housing_units)

##### **Question :** What is the overall trend in housing_units over the period being analyzed?

**Answer :** ``The overall trend in the housing units is increasing over the period but at a declining rate. The growth rate at the start of the period is more; than at the end, meaning it appears to be slowly but gradually declining over the period.``

---

### Calculating and Plotting the Average Sale Prices per Square Foot

Step 1: Grouping data by year, and then averaging the results.

In [5]:
# Creating a numerical aggregation by grouping the data by year and averaging the results

prices_square_foot_by_year = sfo_data_df.groupby("year").mean()

# Reviewing the resulting DataFrame

prices_square_foot_by_year


C:\Users\prath\AppData\Local\Temp\ipykernel_25004\4256561245.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  prices_square_foot_by_year = sfo_data_df.groupby("year").mean()


sale_price_sqr_foot  housing_units  gross_rent
year                                                
2010           369.344353       372560.0      1239.0
2011           341.903429       374507.0      1530.0
2012           399.389968       376454.0      2324.0
2013           483.600304       378401.0      2971.0
2014           556.277273       380348.0      3528.0
2015           632.540352       382295.0      3739.0
2016           697.643709       384242.0      4390.0

##### **Question :** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer :** ``The lowest gross rent reported was in 2010 which is $1,239.00.``

Step 2: Creating a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame will include the averages per year for only the sale price per square foot and the gross rent.

In [6]:
# Creating new dataframe with price per square foot and gross rent

prices_square_foot_by_year = prices_square_foot_by_year.drop(columns=["housing_units"])

# Reviewing the DataFrame

prices_square_foot_by_year


sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

Step 3: Using hvPlot for plotting the `prices_square_foot_by_year` DataFrame as a line plot.

(This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`)

Step 4: Styling and formatting the line plot to ensure a professionally styled visualization.

In [7]:
# Plotting prices_square_foot_by_year. 
# Including labels for the x- and y-axes, and a title.

display(prices_square_foot_by_year.hvplot.line(
    xlabel = "Year",
    ylabel = "Gross Rent / Sale Price Per Square Foot",
    fontscale = 1.3,
    height = 400,
    width = 900,
    title="Sale Price Per Square Foot and Average Gross Rent - 2010-2016 - San Francisco"
))


:NdOverlay   [Variable]
   :Curve   [year]   (value)

##### **Question :** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** ``The year of 2011 experienced a drop in the average sale price per square foot as compared to 2010. Average sale price per square feet in 2010 was $369.34 and was $341.90 in 2011 so, that is a 27.44 dollars drop in average sale price per square foot.``

##### **Question :** If so, did the gross rent increase or decrease during that year?

**Answer:** ``Average gross rent for the year 2011 increased in comparsion to 2010 by $291.00``

---

### Comparing the Average Sale Prices by Neighborhood

Step 1: Creating a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregating the results by the `mean` of the groups.

In [8]:
# Grouping by year and neighborhood and then creating a new dataframe of the mean values

prices_by_year_by_neighborhood = sfo_data_df.groupby(["year", "neighborhood"]).mean()

# Rewing the DataFrame

prices_by_year_by_neighborhood


sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                          
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

Step 2: Filtering out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [9]:
# Filtering out the housing_units

prices_by_year_by_neighborhood.drop(columns=["housing_units"], inplace=True)

# Reviewing the first and last five rows of the DataFrame

display(prices_by_year_by_neighborhood.head())

display(prices_by_year_by_neighborhood.tail())


sale_price_sqr_foot  gross_rent
year neighborhood                                     
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

Step 3: Creating an interactive line plot with hvPlot that visualizes both `sale_price_sqr_foot` and `gross_rent`. Setting the x-axis parameter to the year (`x="year"`). Using the `groupby` parameter to create an interactive widget for `neighborhood`.

Step 4: Styling and formatting the line plot to ensure a professionally styled visualization.

In [10]:
# Using hvplot to create an interactive line plot of the average price per square foot
# The plot will have a dropdown selector for the neighborhood

display(prices_by_year_by_neighborhood.hvplot.line(
    x = "year",
    xlabel = "Year",
    ylabel = "Gross Rent / Sale Price Per Square Foot",
    hover = True,
    hover_color = "Aqua",
    fontscale = 1.3,
    height = 400,
    frame_width = 590,
    groupby = "neighborhood",
    title="Sale Price Per Square Foot and Average Gross Rent - 2010-2016 - By Neighborhood"
))


BokehModel(combine_events=True, render_bundle={'docs_json': {'3abca5c8-8698-4f5a-ad70-253e989a2761': {'version…

##### **Question :** For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer :** ``Using the interactive visualization the average sale price per square foot for 2016 is less than that of 2012.``

---

### Building an Interactive Neighborhood Map

Step 1: Reading the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and creating a DataFrame named `neighborhood_locations_df`. Making sure to set the `index_col` of the DataFrame as “Neighborhood”.

In [11]:
# Loading neighborhoods coordinates data

neighborhoods_coordinates_path = Path(r"C:\Users\prath\UofT\UTOR-VIRT-FIN-PT-08-2023-U-LOLC\06-PyViz\Unit 6 Homework\Instructions\Starter_Code\Resources\neighborhoods_coordinates.csv")

neighborhood_locations_df = pd.read_csv(neighborhoods_coordinates_path, index_col="Neighborhood")

# Reviewing the DataFrame

neighborhood_locations_df


Lat         Lon
Neighborhood                             
Alamo Square        37.791012 -122.402100
Anza Vista          37.779598 -122.443451
Bayview             37.734670 -122.401060
Bayview Heights     37.728740 -122.410980
Bernal Heights      37.728630 -122.443050
...                       ...         ...
West Portal         37.740260 -122.463880
Western Addition    37.792980 -122.435790
Westwood Highlands  37.734700 -122.456854
Westwood Park       37.734150 -122.457000
Yerba Buena         37.792980 -122.396360

[73 rows x 2 columns]

Step 2: Using the original `sfo_data_df` Dataframe, creating a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregating the results by the `mean` of the group.

In [12]:
# Calculating the mean values for each neighborhood

all_neighborhood_info_df = sfo_data_df.drop(columns=["year"]).groupby(["neighborhood"]).mean()

# Reviewing the resulting DataFrame

all_neighborhood_info_df


sale_price_sqr_foot  housing_units   gross_rent
neighborhood                                                       
Alamo Square                 366.020712      378401.00  2817.285714
Anza Vista                   373.382198      379050.00  3031.833333
Bayview                      204.588623      376454.00  2318.400000
Bayview Heights              590.792839      382295.00  3739.000000
Bernal Heights               576.746488      379374.50  3080.333333
...                                 ...            ...          ...
West Portal                  498.488485      376940.75  2515.500000
Western Addition             307.562201      377427.50  2555.166667
Westwood Highlands           533.703935      376454.00  2250.500000
Westwood Park                687.087575      382295.00  3959.000000
Yerba Buena                  576.709848      377427.50  2555.166667

[73 rows x 3 columns]

Step 3: Concatenating the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame into `all_neighborhoods_df`.

In [13]:
# Using the Pandas concat function to join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame

all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis=1,
    join="inner",
    sort=False
)

# Rounding the values of sale_price_sqr_foot and gross_rent

all_neighborhoods_df = round(all_neighborhoods_df, 4)

# Reviewing the DataFrame

display(all_neighborhoods_df.head())

display(all_neighborhoods_df.tail())


Lat       Lon  sale_price_sqr_foot  housing_units  \
Alamo Square      37.7910 -122.4021             366.0207       378401.0   
Anza Vista        37.7796 -122.4435             373.3822       379050.0   
Bayview           37.7347 -122.4011             204.5886       376454.0   
Bayview Heights   37.7287 -122.4110             590.7928       382295.0   
Buena Vista Park  37.7682 -122.4393             452.6806       378076.5   

                  gross_rent  
Alamo Square       2817.2857  
Anza Vista         3031.8333  
Bayview            2318.4000  
Bayview Heights    3739.0000  
Buena Vista Park   2698.8333

Lat       Lon  sale_price_sqr_foot  housing_units  \
West Portal         37.7403 -122.4639             498.4885      376940.75   
Western Addition    37.7930 -122.4358             307.5622      377427.50   
Westwood Highlands  37.7347 -122.4569             533.7039      376454.00   
Westwood Park       37.7342 -122.4570             687.0876      382295.00   
Yerba Buena         37.7930 -122.3964             576.7098      377427.50   

                    gross_rent  
West Portal          2515.5000  
Western Addition     2555.1667  
Westwood Highlands   2250.5000  
Westwood Park        3959.0000  
Yerba Buena          2555.1667

In [14]:
# Calling the dropna function to remove any neighborhoods that do not have data

all_neighborhoods_df = all_neighborhoods_df.dropna().reset_index()

# Renaming the "index" column as "Neighborhood" for use in the Visualization

all_neighborhoods_df = all_neighborhoods_df.rename(columns={
    "index": "Neighborhood"})

# Reviewing the resulting DataFrame

display(all_neighborhoods_df.head())

display(all_neighborhoods_df.tail())


Neighborhood      Lat       Lon  sale_price_sqr_foot  housing_units  \
0      Alamo Square  37.7910 -122.4021             366.0207       378401.0   
1        Anza Vista  37.7796 -122.4435             373.3822       379050.0   
2           Bayview  37.7347 -122.4011             204.5886       376454.0   
3   Bayview Heights  37.7287 -122.4110             590.7928       382295.0   
4  Buena Vista Park  37.7682 -122.4393             452.6806       378076.5   

   gross_rent  
0   2817.2857  
1   3031.8333  
2   2318.4000  
3   3739.0000  
4   2698.8333

Neighborhood      Lat       Lon  sale_price_sqr_foot  housing_units  \
64         West Portal  37.7403 -122.4639             498.4885      376940.75   
65    Western Addition  37.7930 -122.4358             307.5622      377427.50   
66  Westwood Highlands  37.7347 -122.4569             533.7039      376454.00   
67       Westwood Park  37.7342 -122.4570             687.0876      382295.00   
68         Yerba Buena  37.7930 -122.3964             576.7098      377427.50   

    gross_rent  
64   2515.5000  
65   2555.1667  
66   2250.5000  
67   3959.0000  
68   2555.1667

Step 4: Using hvPlot with GeoViews enabled, creating a `points` plot for the `all_neighborhoods_df` DataFrame. Also making sure to:

* Set the `geo` parameter to True.

* Set the `size` parameter to "sale_price_sqr_foot".

* Set the `color` parameter to "gross_rent".

* Set the `tiles` parameter to "OSM".

* Set the `alpha` parameter to "0.75".

* Set the `hover_cols` parameter to "all".

* Set the `use_index` parameter to "False".

* Set the `frame_width` parameter to 700.

* Set the `frame_height` parameter to 500.

* Finally, include a descriptive title.

In [15]:
# Creating a plot to analyze neighborhood info

display(all_neighborhoods_df.hvplot.points(
    "Lon",
    "Lat",
    geo = True,
    size = "sale_price_sqr_foot",
    color = "gross_rent",
    tiles = 'OSM',
    hover_cols = 'all',
    use_index = False,
    alpha = 0.75,
    frame_width = 700,
    frame_height = 500,
    title = "Geographic View of Aggregate of Sale Price Per Square Foot and Gross Rent - 2010-2016 - San Francisco"
))


:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot,Neighborhood,housing_units)

##### **Question :** Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer :** `` According to interactive map neighborhod with the highest gross rent is Westwood Highland with an average gross rent of $3,959.00. Furthermore, the neighborhood with the highest sale price per square foot is Union Square District with an average sale price per square foot of $903.99.``

### Composing a Data Story

Based on the visualizations created, composing a data story that synthesizes the analysis by answering the following questions:

##### **Question :** How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

**Answers :** The trend in rental income growth on an average is more as compared to the trend in sales prices. To add yes, this trend holds true for all neighborhoods across San Francisco.

##### **Question :** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

**Answer :** ``The foremost thing to share for buy-and-rent strategy would be looking for areas with a low sale price per square foot but with a high gross rent trend and more weight should be towards gross rent as such helps with the company's cash flow. For this strategy to work, there are many neighborhoods that are up for grabs like Bayview, Westwood Highlands, Silver Terrace, Visitacoin Valley, Anza Vista, Excelsior and some others. ``